#!/usr/bin/env bash

export KUBERNETES_PROVIDER=aws
export MASTER_SIZE=m3.medium

# staging
#export KUBE_AWS_INSTANCE_PREFIX=staging
#export NUM_NODES=6
#export NODE_SIZE=t2.medium
#export KUBE_AWS_ZONE="us-west-2a"
#kubectl use-context aws_staging

# production
export KUBE_AWS_INSTANCE_PREFIX=kubernetes
export NUM_NODES=4
export NODE_SIZE=c4.xlarge
export KUBE_AWS_ZONE="" # "us-west-2a"
kubectl use-context aws_kubernetes

