#!/usr/bin/env bash

echo "cluster info"
kubectl cluster-info
echo ""

echo "kubernetes info"
kubectl config view
echo ""

elbdomain=$(kubectl describe service web-lb \
    | grep "LoadBalancer Ingress" \
    | awk -F ':' '{print $2}' \
    | awk '{print $1}'
)

echo "to ssh to master node"
echo "ssh -i ~/.ssh/kube_aws_rsa admin@$elbdomain"

